version: '3.9'

services:
  aiohttp_ads_api:
    build: .
    container_name: aiohttp_ads_api
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 8080
      DB_URL: sqlite+aiosqlite:///./data/database.sqlite3
